celo_fnc_druid_init = {
	comment "Exported from Arsenal by [EPJ] Celoush CZ";
	comment "Remove existing items";
	removeAllWeapons _this;
	removeAllItems _this;
	removeAllAssignedItems _this;
	removeUniform _this;
	removeVest _this;
	removeBackpack _this;
	removeHeadgear _this;
	removeGoggles _this;
	comment "Add containers";
	_this forceAddUniform "U_I_GhillieSuit";
	//_this forceAddUniform "U_C_HunterBody_grn";
	_this addHeadgear "H_Bandanna_camo";
	comment "Add weapons";
	_this addMagazine "30Rnd_556x45_Stanag"; 
	_this addWeapon "arifle_Mk20C_F";
	_this addMagazine "30Rnd_556x45_Stanag"; 
	_this addMagazine "30Rnd_556x45_Stanag"; 
	comment "Add items";
	_this linkItem "ItemMap";
	_this linkItem "ItemCompass";
	_this linkItem "ItemWatch";
	_this linkItem "ItemRadio";
	_this linkItem "ItemGPS";
	comment "Set identity";
	_this setFace "GreekHead_A3_05";
	_this setSpeaker "Male01ENGB";
	[_this,"MANW"] call bis_fnc_setUnitInsignia;
};